// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: pokemon.proto

package pokemon_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pokemon_GetLegendaryPokemons_FullMethodName = "/pokemon.Pokemon/GetLegendaryPokemons"
)

// PokemonClient is the client API for Pokemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PokemonClient interface {
	GetLegendaryPokemons(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*PokemonListResponse, error)
}

type pokemonClient struct {
	cc grpc.ClientConnInterface
}

func NewPokemonClient(cc grpc.ClientConnInterface) PokemonClient {
	return &pokemonClient{cc}
}

func (c *pokemonClient) GetLegendaryPokemons(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*PokemonListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PokemonListResponse)
	err := c.cc.Invoke(ctx, Pokemon_GetLegendaryPokemons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokemonServer is the server API for Pokemon service.
// All implementations must embed UnimplementedPokemonServer
// for forward compatibility.
type PokemonServer interface {
	GetLegendaryPokemons(context.Context, *EmptyRequest) (*PokemonListResponse, error)
	mustEmbedUnimplementedPokemonServer()
}

// UnimplementedPokemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPokemonServer struct{}

func (UnimplementedPokemonServer) GetLegendaryPokemons(context.Context, *EmptyRequest) (*PokemonListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLegendaryPokemons not implemented")
}
func (UnimplementedPokemonServer) mustEmbedUnimplementedPokemonServer() {}
func (UnimplementedPokemonServer) testEmbeddedByValue()                 {}

// UnsafePokemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokemonServer will
// result in compilation errors.
type UnsafePokemonServer interface {
	mustEmbedUnimplementedPokemonServer()
}

func RegisterPokemonServer(s grpc.ServiceRegistrar, srv PokemonServer) {
	// If the following call pancis, it indicates UnimplementedPokemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pokemon_ServiceDesc, srv)
}

func _Pokemon_GetLegendaryPokemons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokemonServer).GetLegendaryPokemons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pokemon_GetLegendaryPokemons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokemonServer).GetLegendaryPokemons(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pokemon_ServiceDesc is the grpc.ServiceDesc for Pokemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pokemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pokemon.Pokemon",
	HandlerType: (*PokemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLegendaryPokemons",
			Handler:    _Pokemon_GetLegendaryPokemons_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pokemon.proto",
}
